"""edited pass_hash to pswd

Revision ID: 987021a7e2b5
Revises: b677239eb8df
Create Date: 2026-06-11 01:54:03.310242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '987021a7e2b5'
down_revision: Union[str, Sequence[str], None] = 'b677239eb8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pswd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'pass_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'pswd')
    # ### end Alembic commands ###
